### ISSUE TITLE
Look into adding printing support on report pages

### ISSUE THREAD

**Issue by LeviButcher** [LeviButcher/wvup-tcs#85]

**Comment by a2937** [comment]
You will want create a css file in order to ensure the report pages look best when printed. This web page describes it very well. 

[page](https://www.webcredible.com/blog/print-stylesheet-definitive-guide/)

In order to create the ability to print, the best option appears to be calling it from JavaScript like below. 

`<a href="javascript:window.print()">Click to Print This Page</a>`
